### ISSUE TITLE
Where to enter the API key?

### ISSUE THREAD

**Issue by Fastidious** [waldoj/finds-you#1]
Where on `finds_you.py` one enters the API key?

**Comment by waldoj** [comment]
I've made that more clear [here](https://github.com/waldoj/finds-you/blob/dd9180254e22c3d25de630179750804a89c56ef7/finds_you.py#L75). (I was adding in those lines myself before manually deploying, but including placeholders is more helpful to others!)

**Comment by Fastidious** [comment]
Thank you!
